// <auto-generated />
using System;
using Entity.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CrtiticalDamage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Damage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricDamage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FireDamage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MagicDamage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PoisionDamage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Asset = true,
                            Code = "A1",
                            CrtiticalDamage = 72.0m,
                            Damage = 65m,
                            ElectricDamage = 63.0m,
                            FireDamage = 67.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Espada Larga",
                            PoisionDamage = 31.5m
                        },
                        new
                        {
                            Id = 2,
                            Asset = true,
                            Code = "A2",
                            CrtiticalDamage = 81.0m,
                            Damage = 85m,
                            ElectricDamage = 76.5m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Claymore",
                            PoisionDamage = 63.0m
                        },
                        new
                        {
                            Id = 3,
                            Asset = true,
                            Code = "A3",
                            CrtiticalDamage = 54.0m,
                            Damage = 45m,
                            ElectricDamage = 27.0m,
                            FireDamage = 85.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Daga de Bandido",
                            PoisionDamage = 13.5m
                        },
                        new
                        {
                            Id = 4,
                            Asset = true,
                            Code = "A4",
                            CrtiticalDamage = 76.5m,
                            Damage = 90m,
                            ElectricDamage = 49.5m,
                            FireDamage = 40.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Hacha de Batalla",
                            PoisionDamage = 58.5m
                        },
                        new
                        {
                            Id = 5,
                            Asset = true,
                            Code = "A5",
                            CrtiticalDamage = 67.5m,
                            Damage = 70m,
                            ElectricDamage = 81.0m,
                            FireDamage = 58.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Lanza de Plata",
                            PoisionDamage = 40.5m
                        },
                        new
                        {
                            Id = 6,
                            Asset = true,
                            Code = "A6",
                            CrtiticalDamage = 63.0m,
                            Damage = 60m,
                            ElectricDamage = 90.0m,
                            FireDamage = 36.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Arco Largo",
                            PoisionDamage = 27.0m
                        },
                        new
                        {
                            Id = 7,
                            Asset = true,
                            Code = "A7",
                            CrtiticalDamage = 85.5m,
                            Damage = 95m,
                            ElectricDamage = 54.0m,
                            FireDamage = 31.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Martillo de Guerra",
                            PoisionDamage = 76.5m
                        },
                        new
                        {
                            Id = 8,
                            Asset = true,
                            Code = "A8",
                            CrtiticalDamage = 58.5m,
                            Damage = 75m,
                            ElectricDamage = 58.5m,
                            FireDamage = 76.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Katana de Uchigatana",
                            PoisionDamage = 36.0m
                        },
                        new
                        {
                            Id = 9,
                            Asset = true,
                            Code = "B1",
                            CrtiticalDamage = 45.0m,
                            Damage = 80m,
                            ElectricDamage = 67.5m,
                            FireDamage = 54.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Bastón del Hechicero",
                            PoisionDamage = 22.5m
                        },
                        new
                        {
                            Id = 10,
                            Asset = true,
                            Code = "B2",
                            CrtiticalDamage = 76.5m,
                            Damage = 100m,
                            ElectricDamage = 72.0m,
                            FireDamage = 27.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Espadón Negro",
                            PoisionDamage = 81.0m
                        },
                        new
                        {
                            Id = 11,
                            Asset = true,
                            Code = "B3",
                            CrtiticalDamage = 63.0m,
                            Damage = 55m,
                            ElectricDamage = 45.0m,
                            FireDamage = 81.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Cimitarra",
                            PoisionDamage = 22.5m
                        },
                        new
                        {
                            Id = 12,
                            Asset = true,
                            Code = "B4",
                            CrtiticalDamage = 54.0m,
                            Damage = 95m,
                            ElectricDamage = 85.5m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Lanza del Dragón",
                            PoisionDamage = 49.5m
                        },
                        new
                        {
                            Id = 13,
                            Asset = true,
                            Code = "B5",
                            CrtiticalDamage = 72.0m,
                            Damage = 85m,
                            ElectricDamage = 81.0m,
                            FireDamage = 22.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Ballesta Pesada",
                            PoisionDamage = 54.0m
                        },
                        new
                        {
                            Id = 14,
                            Asset = true,
                            Code = "B6",
                            CrtiticalDamage = 49.5m,
                            Damage = 40m,
                            ElectricDamage = 22.5m,
                            FireDamage = 90.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Daga de Parry",
                            PoisionDamage = 9.0m
                        },
                        new
                        {
                            Id = 15,
                            Asset = true,
                            Code = "B7",
                            CrtiticalDamage = 67.5m,
                            Damage = 80m,
                            ElectricDamage = 67.5m,
                            FireDamage = 49.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Espada Flamberge",
                            PoisionDamage = 45.0m
                        },
                        new
                        {
                            Id = 16,
                            Asset = true,
                            Code = "B8",
                            CrtiticalDamage = 81.0m,
                            Damage = 105m,
                            ElectricDamage = 45.0m,
                            FireDamage = 36.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Hacha Demoniaca",
                            PoisionDamage = 72.0m
                        },
                        new
                        {
                            Id = 17,
                            Asset = true,
                            Code = "C1",
                            CrtiticalDamage = 58.5m,
                            Damage = 70m,
                            ElectricDamage = 85.5m,
                            FireDamage = 54.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Arco Compuesto",
                            PoisionDamage = 31.5m
                        },
                        new
                        {
                            Id = 18,
                            Asset = true,
                            Code = "C2",
                            CrtiticalDamage = 81.0m,
                            Damage = 75m,
                            ElectricDamage = 40.5m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Maza de Hierro",
                            PoisionDamage = 49.5m
                        },
                        new
                        {
                            Id = 19,
                            Asset = true,
                            Code = "C3",
                            CrtiticalDamage = 22.5m,
                            Damage = 110m,
                            ElectricDamage = 63.0m,
                            FireDamage = 58.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Espada Cristalina",
                            PoisionDamage = 40.5m
                        },
                        new
                        {
                            Id = 20,
                            Asset = true,
                            Code = "C4",
                            CrtiticalDamage = 58.5m,
                            Damage = 60m,
                            ElectricDamage = 31.5m,
                            FireDamage = 76.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Garra de Lobo",
                            PoisionDamage = 18.0m
                        },
                        new
                        {
                            Id = 21,
                            Asset = true,
                            Code = "C5",
                            CrtiticalDamage = 40.5m,
                            Damage = 85m,
                            ElectricDamage = 72.0m,
                            FireDamage = 49.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Bastón de Llamas",
                            PoisionDamage = 27.0m
                        },
                        new
                        {
                            Id = 22,
                            Asset = true,
                            Code = "C6",
                            CrtiticalDamage = 72.0m,
                            Damage = 95m,
                            ElectricDamage = 67.5m,
                            FireDamage = 40.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Espada del Caballero Negro",
                            PoisionDamage = 58.5m
                        },
                        new
                        {
                            Id = 23,
                            Asset = true,
                            Code = "C7",
                            CrtiticalDamage = 54.0m,
                            Damage = 50m,
                            ElectricDamage = 27.0m,
                            FireDamage = 85.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Puñales Gemelos",
                            PoisionDamage = 18.0m
                        },
                        new
                        {
                            Id = 24,
                            Asset = true,
                            Code = "C8",
                            CrtiticalDamage = 63.0m,
                            Damage = 90m,
                            ElectricDamage = 76.5m,
                            FireDamage = 54.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Lanza de Plata Divina",
                            PoisionDamage = 45.0m
                        },
                        new
                        {
                            Id = 25,
                            Asset = true,
                            Code = "D1",
                            CrtiticalDamage = 90.0m,
                            Damage = 120m,
                            ElectricDamage = 49.5m,
                            FireDamage = 18.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Martillo del Titán",
                            PoisionDamage = 90.0m
                        },
                        new
                        {
                            Id = 26,
                            Asset = true,
                            Code = "D2",
                            CrtiticalDamage = 67.5m,
                            Damage = 65m,
                            ElectricDamage = 76.5m,
                            FireDamage = 63.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Arco de Cazador",
                            PoisionDamage = 22.5m
                        },
                        new
                        {
                            Id = 27,
                            Asset = true,
                            Code = "D3",
                            CrtiticalDamage = 36.0m,
                            Damage = 100m,
                            ElectricDamage = 58.5m,
                            FireDamage = 63.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Espada Maldita",
                            PoisionDamage = 40.5m
                        },
                        new
                        {
                            Id = 28,
                            Asset = true,
                            Code = "D4",
                            CrtiticalDamage = 76.5m,
                            Damage = 85m,
                            ElectricDamage = 90.0m,
                            FireDamage = 36.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Alabarda",
                            PoisionDamage = 67.5m
                        },
                        new
                        {
                            Id = 29,
                            Asset = true,
                            Code = "D5",
                            CrtiticalDamage = 58.5m,
                            Damage = 55m,
                            ElectricDamage = 63.0m,
                            FireDamage = 72.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Estoque",
                            PoisionDamage = 22.5m
                        },
                        new
                        {
                            Id = 30,
                            Asset = true,
                            Code = "D6",
                            CrtiticalDamage = 85.5m,
                            Damage = 110m,
                            ElectricDamage = 54.0m,
                            FireDamage = 22.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Hacha Gigante",
                            PoisionDamage = 85.5m
                        },
                        new
                        {
                            Id = 31,
                            Asset = true,
                            Code = "D7",
                            CrtiticalDamage = 49.5m,
                            Damage = 75m,
                            ElectricDamage = 67.5m,
                            FireDamage = 58.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Bastón de Hielo",
                            PoisionDamage = 27.0m
                        },
                        new
                        {
                            Id = 32,
                            Asset = true,
                            Code = "D8",
                            CrtiticalDamage = 27.0m,
                            Damage = 45m,
                            ElectricDamage = 54.0m,
                            FireDamage = 81.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Cuchillo Arrojadizo",
                            PoisionDamage = 13.5m
                        },
                        new
                        {
                            Id = 33,
                            Asset = true,
                            Code = "E1",
                            CrtiticalDamage = 54.0m,
                            Damage = 105m,
                            ElectricDamage = 72.0m,
                            FireDamage = 54.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Espada de Moonlight",
                            PoisionDamage = 49.5m
                        },
                        new
                        {
                            Id = 34,
                            Asset = true,
                            Code = "E2",
                            CrtiticalDamage = 63.0m,
                            Damage = 70m,
                            ElectricDamage = 76.5m,
                            FireDamage = 67.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Lanza Alada",
                            PoisionDamage = 36.0m
                        },
                        new
                        {
                            Id = 35,
                            Asset = true,
                            Code = "E3",
                            CrtiticalDamage = 76.5m,
                            Damage = 115m,
                            ElectricDamage = 45.0m,
                            FireDamage = 27.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Martillo del Caos",
                            PoisionDamage = 81.0m
                        },
                        new
                        {
                            Id = 36,
                            Asset = true,
                            Code = "E4",
                            CrtiticalDamage = 63.0m,
                            Damage = 60m,
                            ElectricDamage = 72.0m,
                            FireDamage = 63.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 10m,
                            Name = "Ballesta Ligera",
                            PoisionDamage = 31.5m
                        },
                        new
                        {
                            Id = 37,
                            Asset = true,
                            Code = "E5",
                            CrtiticalDamage = 67.5m,
                            Damage = 65m,
                            ElectricDamage = 49.5m,
                            FireDamage = 76.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Espada Curva",
                            PoisionDamage = 31.5m
                        },
                        new
                        {
                            Id = 38,
                            Asset = true,
                            Code = "E6",
                            CrtiticalDamage = 45.0m,
                            Damage = 55m,
                            ElectricDamage = 85.5m,
                            FireDamage = 67.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Látigo Espinoso",
                            PoisionDamage = 27.0m
                        },
                        new
                        {
                            Id = 39,
                            Asset = true,
                            Code = "E7",
                            CrtiticalDamage = 36.0m,
                            Damage = 95m,
                            ElectricDamage = 76.5m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Bastón del Archimago",
                            PoisionDamage = 31.5m
                        },
                        new
                        {
                            Id = 40,
                            Asset = true,
                            Code = "E8",
                            CrtiticalDamage = 81.0m,
                            Damage = 100m,
                            ElectricDamage = 58.5m,
                            FireDamage = 31.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Hacha de Ejecutor",
                            PoisionDamage = 72.0m
                        },
                        new
                        {
                            Id = 41,
                            Asset = true,
                            Code = "F1",
                            CrtiticalDamage = 49.5m,
                            Damage = 50m,
                            ElectricDamage = 31.5m,
                            FireDamage = 81.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Daga Venenosa",
                            PoisionDamage = 18.0m
                        },
                        new
                        {
                            Id = 42,
                            Asset = true,
                            Code = "F2",
                            CrtiticalDamage = 58.5m,
                            Damage = 90m,
                            ElectricDamage = 90.0m,
                            FireDamage = 40.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Arco del Cazador de Dragones",
                            PoisionDamage = 45.0m
                        },
                        new
                        {
                            Id = 43,
                            Asset = true,
                            Code = "F3",
                            CrtiticalDamage = 63.0m,
                            Damage = 85m,
                            ElectricDamage = 63.0m,
                            FireDamage = 63.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Espada del Crepúsculo",
                            PoisionDamage = 40.5m
                        },
                        new
                        {
                            Id = 44,
                            Asset = true,
                            Code = "F4",
                            CrtiticalDamage = 67.5m,
                            Damage = 80m,
                            ElectricDamage = 81.0m,
                            FireDamage = 54.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Tridente de Poseidón",
                            PoisionDamage = 49.5m
                        },
                        new
                        {
                            Id = 45,
                            Asset = true,
                            Code = "F5",
                            CrtiticalDamage = 76.5m,
                            Damage = 70m,
                            ElectricDamage = 45.0m,
                            FireDamage = 49.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Maza de Plata",
                            PoisionDamage = 45.0m
                        },
                        new
                        {
                            Id = 46,
                            Asset = true,
                            Code = "F6",
                            CrtiticalDamage = 54.0m,
                            Damage = 90m,
                            ElectricDamage = 58.5m,
                            FireDamage = 58.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Espada de Llamas",
                            PoisionDamage = 36.0m
                        },
                        new
                        {
                            Id = 47,
                            Asset = true,
                            Code = "F7",
                            CrtiticalDamage = 72.0m,
                            Damage = 75m,
                            ElectricDamage = 85.5m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Guja",
                            PoisionDamage = 54.0m
                        },
                        new
                        {
                            Id = 48,
                            Asset = true,
                            Code = "F8",
                            CrtiticalDamage = 76.5m,
                            Damage = 80m,
                            ElectricDamage = 67.5m,
                            FireDamage = 54.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Espada Bastarda",
                            PoisionDamage = 49.5m
                        },
                        new
                        {
                            Id = 49,
                            Asset = true,
                            Code = "G1",
                            CrtiticalDamage = 45.0m,
                            Damage = 75m,
                            ElectricDamage = 76.5m,
                            FireDamage = 72.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Ballesta del Asesino",
                            PoisionDamage = 27.0m
                        },
                        new
                        {
                            Id = 50,
                            Asset = true,
                            Code = "G2",
                            CrtiticalDamage = 81.0m,
                            Damage = 105m,
                            ElectricDamage = 49.5m,
                            FireDamage = 36.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Martillo de Tormenta",
                            PoisionDamage = 76.5m
                        },
                        new
                        {
                            Id = 51,
                            Asset = true,
                            Code = "G3",
                            CrtiticalDamage = 40.5m,
                            Damage = 60m,
                            ElectricDamage = 36.0m,
                            FireDamage = 85.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Daga de Sombras",
                            PoisionDamage = 16.2m
                        },
                        new
                        {
                            Id = 52,
                            Asset = true,
                            Code = "G4",
                            CrtiticalDamage = 45.0m,
                            Damage = 110m,
                            ElectricDamage = 67.5m,
                            FireDamage = 49.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Espada del Alma",
                            PoisionDamage = 45.0m
                        },
                        new
                        {
                            Id = 53,
                            Asset = true,
                            Code = "G5",
                            CrtiticalDamage = 54.0m,
                            Damage = 65m,
                            ElectricDamage = 76.5m,
                            FireDamage = 63.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 20m,
                            Name = "Lanza de Hueso",
                            PoisionDamage = 31.5m
                        },
                        new
                        {
                            Id = 54,
                            Asset = true,
                            Code = "G6",
                            CrtiticalDamage = 31.5m,
                            Damage = 100m,
                            ElectricDamage = 81.0m,
                            FireDamage = 40.5m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Bastón de Rayo",
                            PoisionDamage = 36.0m
                        },
                        new
                        {
                            Id = 55,
                            Asset = true,
                            Code = "G7",
                            CrtiticalDamage = 72.0m,
                            Damage = 95m,
                            ElectricDamage = 40.5m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 30m,
                            Name = "Hacha de Carnicero",
                            PoisionDamage = 63.0m
                        },
                        new
                        {
                            Id = 56,
                            Asset = true,
                            Code = "G8",
                            CrtiticalDamage = 63.0m,
                            Damage = 120m,
                            ElectricDamage = 72.0m,
                            FireDamage = 45.0m,
                            Image = "assets/armas.png",
                            IsDeleted = false,
                            MagicDamage = 40m,
                            Name = "Espada del Destino",
                            PoisionDamage = 54.0m
                        });
                });

            modelBuilder.Entity("Entity.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("bit");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEarned")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GamePlayerId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Entity.Models.GamePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<bool>("Winner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoomId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Entity.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Entity.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asset")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Entity.Models.Deck", b =>
                {
                    b.HasOne("Entity.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.GamePlayer", "GamePlayer")
                        .WithMany()
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("Entity.Models.GamePlayer", b =>
                {
                    b.HasOne("Entity.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
